model:
  type: resnet18
dataset: cifar10
aug: divaug
divaug:
  N: 2
  C: 4
  S: 2
batch: 512
epoch: 200
lr_schedule:
  type: 'cosine'
optimizer:
  lr: 0.1
  type: sgd
  nesterov: True
  decay: 0.0005
mixed_precsion: True