model:
  type: shakeshake26_2x96d
dataset: cifar10
aug: divaug
divaug:
  N: 2
  C: 8
  S: 4
batch: 128
epoch: 600
lr_schedule:
  type: 'cosine'
optimizer:
  lr: 0.2
  type: sgd
  nesterov: True
  decay: 0.0001