model:
  type: wresnet28_2
dataset: cifar10
aug: divaug
divaug:
  N: 2
  C: 4
  S: 2
batch: 32
train_size: 2000
batch_unsup: 448
ratio_unsup: 5.0
softmax_temp: 0.4
confidence_threshold: 0.8
ratio_mode: 'linear'
epoch: 3200
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 300
    epoch: 120
optimizer:
  lr: 0.0001
  type: sgd
  nesterov: True
  decay: 0.0005
